#                                                                                                                   
# One Convergence, Inc. CONFIDENTIAL                                                                                
# Copyright (c) 2012-2014, One Convergence, Inc., USA                                                               
# All Rights Reserved.                                                                                              
#                                                                                                                   
# All information contained herein is, and remains the property of                                                  
# One Convergence, Inc. and its suppliers, if any. The intellectual and                                             
# technical concepts contained herein are proprietary to One Convergence,                                           
# Inc. and its suppliers.                                                                                           
#                                                                                                                   
# Dissemination of this information or reproduction of this material is                                             
# strictly forbidden unless prior written permission is obtained from
# One Convergence, Inc., USA
#

########################################################################
#    Project: Ansible NSD Install                                      # 
#    Team/Authors:                                                     #                                            
#            Venkat Akkina [venkat.akkina@oneconvergence.com]          #                                            
#            Harshal Wagh  [harshal.wagh@oneconvergence.com]           #                                            
#            Deekshith Patnala [deekshith.patnala@oneconvergence.com]  #                                            
########################################################################    



---
-
  hosts: build
  sudo: true
  tasks:
    -
      block:
        -
          name: "get timestamp"
          register: ts
          shell: "date +%F_%T | tr : -"
        -
          set_fact: "timestamp={{ts.stdout}}"
      when: "timestamp is not defined"
    -
      debug: "msg={{timestamp}}"
-
  hosts: controller
  tasks:
    -
      set_fact: "build_server=\"{{groups['build'][0]}}\""
    -
      debug: "msg=\"{{build_server}}\""
    -
      block:
        -
          name: "check whether nsd_install_directory exist or not"
          register: p
          stat: "path={{nsd_install_dir}}"
        -
          debug: "msg=\"nsd_install directory already exist\""
          when: "p.stat.isdir is defined and p.stat.isdir"
        -
          file: "path=\"{{nsd_install_dir}}\" state=absent"
          name: "delete existing nsd_install_dir"
          when: "p.stat.isdir is defined and p.stat.isdir"
        -
          name: "Create nsd_install_directory"
          shell: "mkdir -p {{nsd_install_dir}}"
        - 
          delegate_to: "{{build_server}}"
          synchronize: "src={{license_json_file}} dest={{nsd_install_dir}}"
          name: "copy license_json_file from build server to OSController"
        - 
          delegate_to: "{{build_server}}"
          synchronize: "src={{upload_license_sh_file}} dest={{nsd_install_dir}}"
          name: "copy upload_license_sh_file from build server to OSController"
        - 
          delegate_to: "{{build_server}}"
          synchronize: "src={{openstack_nsd_packages_tar}} dest={{nsd_install_dir}}"
          name: "copy openstack_nsd_packages_tar from build server to OSController"

        -
          find: "paths={{nsd_install_dir}} patterns=\"*openstack-nsd-packages*\" recurse=yes"
          name: "Find the openstack-nsd-packages tar "
          register: nsd_packages_tar_path
        -
          debug: "msg={{nsd_packages_tar_path.files[0].path}}"
        -
          args:
            chdir: "{{nsd_install_dir}}"
          name: "Extract openstack-nsd-packages tar"
          shell: "tar -zxf {{nsd_packages_tar_path.files[0].path}}"
        -
          find: "paths={{nsd_install_dir}} patterns=\"*openstack-nfp*\" recurse=yes"
          name: "Find the openstack-nfp tar"
          register: openstack_nfp_tar_path
        -
          debug: "msg={{openstack_nfp_tar_path.files[0].path}}"
        -
          args:
            chdir: "{{nsd_install_dir}}"
          name: "Extract openstack-nfp tar"
          shell: "tar -zxf {{openstack_nfp_tar_path.files[0].path}}"
        -
          args:
            chdir: "{{nsd_install_dir}}/openstack-nfp"
          name: "Install NFP on OS controller"
          shell: "bash install_nfp.sh"
        -
          find: "paths={{nsd_install_dir}} patterns=\"*openstack-nsd*.rpm\" recurse=yes"
          name: "Find the openstack-nsd rpm"
          register: nsd_rpm_path
        -
          debug: "msg={{nsd_rpm_path.files[0].path}}"
        -
          name: "Install NSD RPM on OS controller"
          yum: "name={{nsd_rpm_path.files[0].path}} state=present"
        -
          name: "check whether default_ip_pool is already configured or not"
          register: res
          ignore_errors: True
          shell: "crudini --get /etc/neutron/neutron.conf group_policy_implicit_policy default_ip_pool"
        -
          debug: "msg= default_ip_pool is already configured and it is {{res.stdout}}"
          when: "res.stdout != \"\""
        -
          name: "configure default ip pool"
          shell: "crudini --set /etc/neutron/neutron.conf group_policy_implicit_policy default_ip_pool {{default_ip_pool}}"
          when: "res.stdout == \"\""
        -
          name: "check whether default_proxy_ip_pool is already configured or not"
          register: res
          ignore_errors: True
          shell: "crudini --get /etc/neutron/neutron.conf group_policy_implicit_policy default_proxy_ip_pool"
        -
          debug: "msg= default_proxy_ip_pool is already configured and it is {{res.stdout}}"
          when: "res.stdout != \"\""
        -
          name: "configure default proxy ip pool"
          shell: "crudini --set /etc/neutron/neutron.conf group_policy_implicit_policy default_proxy_ip_pool {{default_proxy_ip_pool}}"
          when: "res.stdout == \"\""
        -
          name: "configure orchestrator"
          shell: "python /usr/lib/python2.7/site-packages/gbpservice/contrib/nfp/tools/setup_nfp.py --configure"
        -
          name: "Configure NSD"
          shell: "python /usr/lib/python2.7/site-packages/gbpservice/nsd/tools/setup_nsd.py --configure-nsd"
        -
          find: "paths={{nsd_install_dir}} patterns=\"*nsd-sslvpn*.rpm\" recurse=yes"
          name: "Find the nsd-sslvpn rmp"
          register: sslvpn_rpm_path

        - name: "install sslvpn"
          shell: "rpm -ivh --force {{sslvpn_rpm_path.files[0].path}}"
        - 
          name: "Add different host filter configuration in nova.conf"
          shell: "crudini --set /etc/nova/nova.conf DEFAULT scheduler_default_filters \"`crudini --get /etc/nova/nova.conf DEFAULT scheduler_default_filters`,DifferentHostFilter\""
        - 
          name: "Restart Nova"
          shell: "openstack-service restart nova"

      when: "deploy_nsd == 'true'"
-
  hosts: "controller[0]"
  tasks:
    -
      block:
        -
          set_fact: "build_server={{groups['build'][0]}}"
        -
          name: "start orchestrator"
          shell: "python /usr/lib/python2.7/site-packages/gbpservice/contrib/nfp/tools/setup_nfp.py --enable-orchestrator"

        -
          environment:
            OS_AUTH_URL: "http://{{ inventory_hostname }}:5000/v2.0"
            OS_PASSWORD: "{{os_password}}"
            OS_REGION_NAME: "{{os_region_name}}"
            OS_TENANT_NAME: "{{os_tenant_name}}"
            OS_USERNAME: "{{os_username}}"
          name: "check whether heat_stack_role is already added or not"
          register: res
          ignore_errors: True
          shell: "openstack user role list | grep neutron | grep -c heat_stack_owner"

        - debug: "msg=\"heat stack role is already added\"" 
          when: "res.rc != 1"
        -
          environment:
            OS_AUTH_URL: "http://{{ inventory_hostname }}:5000/v2.0"
            OS_PASSWORD: "{{os_password}}"
            OS_REGION_NAME: "{{os_region_name}}"
            OS_TENANT_NAME: "{{os_tenant_name}}"
            OS_USERNAME: "{{os_username}}"
          name: "add heat_stack_role"
          shell: "openstack role add --project services --user neutron heat_stack_owner"
          when: "res.rc == 1"
        -
          name: "create nfp resources"
          shell: "python /usr/lib/python2.7/site-packages/gbpservice/contrib/nfp/tools/setup_nfp.py --create-resources"
        -
          name: "create HA resources"
          shell: "python /usr/lib/python2.7/site-packages/gbpservice/nsd/tools/setup_nsd.py --create-ha-resources"

        -
          delegate_to: "{{build_server}}"
          synchronize: "src={{openstack_nsd_images_tar}} dest={{nsd_install_dir}}"
          name: "copy openstack_nsd_images_tar from build server to OSController"

        -
          find: "paths={{nsd_install_dir}} patterns=\"*openstack-nsd-images*\" recurse=yes"
          name: "Find the openstack-nsd-images tar rmp"
          register: nsd_images_tar_path
        -
          debug: "msg={{nsd_images_tar_path.files[0].path}}"
        -
          args:
            chdir: "{{nsd_install_dir}}"
          name: "Extract openstack-nsd-images tar"
          shell: "tar -xzf {{nsd_images_tar_path.files[0].path}}"

        - find: "paths={{nsd_install_dir}} patterns=*NSD_Images* recurse=yes file_type=directory"
          name: "Find the NSD-images directory"
          register: NSD_images_path

        - debug: "msg={{NSD_images_path.files[0].path}}"
        -
          find: "paths={{NSD_images_path.files[0].path}} patterns=\"*nsd_controller*.qcow2\" recurse=yes"
          name: "Find the nsd_controller qcow image"
          register: nsd_controller
        -
          debug: "msg={{nsd_controller.files[0].path}}"
        -
          args:
            chdir: "{{NSD_images_path.files[0].path}}"
          name: "Launch NSD Controller VM"
          shell: "python /usr/lib/python2.7/site-packages/gbpservice/nsd/tools/setup_nsd.py --launch-controller --nsd-controller-image-path {{nsd_controller.files[0].path}}"
        -
          args:
            chdir: "{{NSD_images_path.files[0].path}}"
          name: "Upload NSD Images to OpenStack glance"
          shell: "bash setup_nsd_images.sh --operation=upload --vyos_path=service_images/vyos.qcow2 --haproxy_lbaasv1_path=service_images/haproxy_lbaasv1.qcow2 --haproxy_lbaasv2_path=service_images/haproxy_lbaasv2.qcow2 --asav_path=service_images/asav.qcow2"
        -
          environment:
            OS_AUTH_URL: "http://{{ inventory_hostname }}:5000/v2.0"
            OS_PASSWORD: "{{os_password}}"
            OS_REGION_NAME: "{{os_region_name}}"
            OS_TENANT_NAME: "{{os_tenant_name}}"
            OS_USERNAME: "{{os_username}}"
          name: "find controller VM ip"
          register: nsd_controller_VM_ip
          shell: neutron port-list | grep controller | cut -d'"' -f8
        -
          debug: msg="{{nsd_controller_VM_ip.stdout}}"
        -
          set_fact: "controller_ip={{ nsd_controller_VM_ip.stdout }}"
        -
          debug: "msg={{controller_ip}}"
      when: "deploy_nsd == 'true'"

-
  hosts: network
  tasks:
    -
      set_fact: "build_server={{groups['build'][0]}}"
    -
      debug: "msg={{build_server}}"
    -
      set_fact: "OSC={{ hostvars[groups['controller'][0]]['inventory_hostname']}}"
    -
      set_fact: "NC={{ hostvars[groups['network'][0]]['inventory_hostname']}}"
    -
      debug: "msg={{OSC}}"
    -
      debug: "msg={{NC}}"
    -
      block:
        -
          name: "yum crudini"
          yum: "name=crudini state=present"
        -
          name: "yum telnet"
          yum: "name=telnet state=present"
        -
          block:
            -
              name: "check whether nsd_install_directory exist or not"
              register: p
              stat: "path={{nsd_install_dir}}"
            -
              debug: "msg=\"Path exists and is a directory\""
              when: "p.stat.isdir is defined and p.stat.isdir"
            -
              file: "path=\"{{nsd_install_dir}}\" state=absent"
              name: "delete existing nsd_install_dir"
              when: "p.stat.isdir is defined and p.stat.isdir"
            -
              name: "Create nsd_install_directory"
              shell: "mkdir -p {{nsd_install_dir}}"
            -
              delegate_to: "{{build_server}}"
              synchronize: "src={{openstack_nsd_packages_tar}} dest={{nsd_install_dir}}"
            -
              find: "paths={{nsd_install_dir}} patterns=\"*openstack-nsd-packages*\" recurse=yes"
              name: "Find the openstack-nsd-packages tar rmp"
              register: nsd_packages_tar_path
            -
              debug: "msg={{nsd_packages_tar_path.files[0].path}}"
            -
              args:
                chdir: "{{nsd_install_dir}}"
              name: "Extract openstack-nsd-packages tar"
              shell: "tar -zxf {{nsd_packages_tar_path.files[0].path}}"
            -
              find: "paths={{nsd_install_dir}} patterns=\"*openstack-nfp*\" recurse=yes"
              name: "Find the openstack-nfp tar rmp"
              register: openstack_nfp_tar_path
            -
              debug: "msg={{openstack_nfp_tar_path.files[0].path}}"
            -
              args:
                chdir: "{{nsd_install_dir}}"
              name: "Extract openstack-nfp tar"
              shell: "tar -zxf {{openstack_nfp_tar_path.files[0].path}}"
            -
              block:
                -
                  find: "paths={{nsd_install_dir}} patterns=\"*openstack-neutron-gbp*.rpm\" recurse=yes"
                  name: "Find the openstack-neutron-gbp rmp"
                  register: neutron_gbp_rpm_path
                -
                  debug: "msg={{neutron_gbp_rpm_path.files[0].path}}"
                -
                  name: "Install openstack-neutron-gbp"
                  yum: "name={{neutron_gbp_rpm_path.files[0].path}} state=present"

                -
                  name: "yum neutronclient"
                  yum: "name=python-neutronclient state=present"
                -
                  name: "yum gbpclient"
                  yum: "name=python-gbpclient state=present"
              when: "ACI_setup != true"
            -
              args:
                chdir: "{{nsd_install_dir}}/openstack-nfp"
              name: "Install NFP on OS controller"
              shell: "bash install_nfp.sh"
            -
              find: "paths={{nsd_install_dir}} patterns=\"*openstack-nsd*.rpm\" recurse=yes"
              name: "Find the openstack-nsd rmp"
              register: nsd_rpm_path
            -
              debug: "msg={{nsd_rpm_path.files[0].path}}"
            -
              name: "Install NSD RPM on OS controller"
              yum: "name={{nsd_rpm_path.files[0].path}} state=present"
            -
              find: "paths={{nsd_install_dir}} patterns=\"*nsd-sslvpn*.rpm\" recurse=yes"
              name: "Find the nsd-sslvpn rmp"
              register: sslvpn_rpm_path

            - name: "install sslvpn"
              shell: "rpm -ivh --force {{sslvpn_rpm_path.files[0].path}}"
            #  yum: "name={{sslvpn_rpm_path.files[0].path}} state=present"

          when: "OSC != NC"
        -
          name: "Configure NSD modules"
          shell: "crudini --set /etc/nfp.ini PROXY_AGENT nfp_modules_path `crudini --get /etc/nfp.ini PROXY_AGENT nfp_modules_path`,gbpservice.nsd.proxy_agent.modules"
        -
          name: "Enable nfp proxy. This enables and runs NFP proxy component"
          shell: "python /usr/lib/python2.7/site-packages/gbpservice/contrib/nfp/tools/setup_nfp.py --enable-proxy"
        -
          name: "Update NSD Controller VM IP in /etc/nfp.ini file"
          shell: "crudini --set /etc/nfp.ini PROXY nfp_controller_ip {{hostvars[groups['controller'][0]]['controller_ip'] }}"
        -
          name: "restart proxy services"
          shell: "systemctl restart nfp_proxy"
        -
          name: "restart proxy_agent services"
          shell: "systemctl restart nfp_proxy_agent"
      when: "deploy_nsd == 'true'"
