--- 
- 
  hosts: build
  sudo: true
  tasks: 
    - 
      block: 
        - 
          name: "get timestamp"
          register: ts
          shell: "date +%F_%T | tr : -"
        - 
          set_fact: "timestamp={{ts.stdout}}"
          when: "timestamp is not defined"
        - 
          debug: "msg={{timestamp}}"
    - 
      block: 
        - 
          block: 
            - 
              set_fact: image_build_directory=/opt/atf-build
          when: "deploy_atf == 'true'"
        - 
          block: 
            - 
              name: "get the latest image directory"
              register: image_dir
              shell: "ls -t {{images_directory}}| grep images | sed -n '1p'"
            - 
              debug: "msg={{image_dir.stdout}}"
            - 
              set_fact: "image_install_directory={{images_directory}}/images.{{timestamp}}"
            - 
              debug: "msg={{timestamp}}"
            - 
              debug: "msg={{ image_build_directory }}"
            - 
              debug: "msg={{ image_install_directory }}"
            - 
              name: "Make the root build directory"
              shell: "mkdir -p {{ image_build_directory }}"
            - 
              name: "Make the root install directory"
              shell: "mkdir -p {{ image_install_directory }}"
            - 
              name: "copy files from latest image directory if images were not built during this build"
              shell: "cp {{images_directory}}/{{image_dir.stdout}}/* {{image_install_directory}}/."
          when: "image_install_directory_set is not defined"
        - 
          name: "Make rpm-build directory"
          shell: "mkdir -p {{images_directory}}/rpm-build.{{timestamp}}"
        - 
          copy: "src=config/commands-rpms dest={{images_directory}}/rpm-build.{{timestamp}}"
          name: "Copy docker commands file,"
        - 
          args: 
            chdir: "{{images_directory}}/rpm-build.{{timestamp}}"
          name: "build rpms"
          register: cmd_log
          shell: "cat commands-rpms | docker run -i --name nfp_gbp_builder.ans  --rm -v ${PWD}:/nfp nfp-gbp-rpm-builder"

        - debug: msg="{{cmd_log.stdout_lines}}"
        - 
          args: 
            chdir: "{{image_install_directory}}"
          name: "move the RPMs"
          shell: "cp {{images_directory}}/rpm-build.{{timestamp}}/*.* ."
        # - 
        #   block: 
        #     - 
        #       name: "Copy images to jenkins"
        #       synchronize: "mode=pull src={{image_install_directory}} dest={{images_directory}}"
        #   when: "copy_images_to_jenkins == 'true'"
        - 
          name: "remove rpm-build directory"
          shell: "rm -rf {{images_directory}}/rpm-build.{{timestamp}}"
        # - 
        #   shell: "rm -rf {{image_build_directory}}/nsd-build/"
        #   name: "clean up nsd-build"

      when: "build_rpms == 'true'"

